[computer]
num_qubits = 2

[circuit]
ansatz = "sel"
num_layers = 1
conv_layer = "FreeVatanWilliams"

[dataset]
dataset_size = 20
batch_size = 0

[training]
optimizer = "numpy"
max_iters = 1000
abstol = 1.0e-5
step_size = 1.0e-3

[domain]
x0 = 0.0
xf = 1.0

[problem]
problem_type = "fit"

[output]
folder_name = "~/fit_0"
