[computer]
num_qubits = 4
num_layers = 2
ansatz = "sel" # sel or conv

[dataset]
dataset_size = 20
batch_size = 0

[training]
optimizer = "numpy" # numpy or torch
max_iters = 1000
abstol = 1.0e-5
step_size = 1.0e-3

[domain]
x0 = 0.0
xf = 1.0

[problem]
problem_type = "hagen-poiseuille"

[hagen-poiseuille-params]
G = 1.0
R = 1.0
mu = 1.0

[output]
folder_name = "hagen_poiseuille"
