[computer]
num_qubits = 4
num_layers = 1
ansatz = "sel" # sel or conv

[dataset]
dataset_size = 20
batch_size = 0

[training]
optimizer = "numpy" # numpy or torch
max_iters = 5
abstol = 1.0e-5
step_size = 1.0e-3

[domain]
x0 = 0.0
xf = 1.0

[problem]
problem_type = "fit"

[output]
folder_name = "fit_line"
