[computer]
num_qubits = 4
num_layers = 3
ansatz = "conv" # sel or conv

[dataset]
dataset_size = 20
batch_size = 0

[training]
optimizer = "torch" # numpy or torch
max_iters = 10
abstol = 1.0e-5
step_size = 1.0e-4

[domain]
x0 = 0.0
xf = 1.0

[hagen-poiseuille-params]
G = 1.0
R = 1.0
mu = 1.0

[output]
folder_name = "plane_hagen_poiseuille"
