[computer]
num_qubits = 5
num_layers = 3

[dataset]
dataset_size = 20
batch_size = 0

[training]
folder_name = "hagen_poiseuille"
max_iters = 10
abstol = 1.0e-2
step_size = 1.0e-3

[domain]
x0 = 0.0
xf = 1.0

[hagen-poiseuille-params]
G = 1.0
R = 1.0
mu = 1.0