site_name: QCNN Toolkit Documentation

theme:
  name: "mkdocs"

nav:
  - Home: index.md
  - API Documentation: api.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]